package ai.openspace.backgroundupload

import android.util.Log
import androidx.work.ExistingWorkPolicy
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkInfo
import androidx.work.WorkManager
import androidx.work.workDataOf
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableArray
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableArray
import com.facebook.react.bridge.WritableMap
import com.google.gson.Gson
import java.io.File
import java.nio.file.Files
import java.nio.file.StandardCopyOption


/**
 * TurboModule (New Architecture). [NativeRNFileUploaderSpec] is generated by
 * codegen from `src/NativeRNFileUploader.ts` into this same package (see
 * `codegenConfig.android.javaPackageName` in package.json), so it needs no import.
 */
class UploaderModule(context: ReactApplicationContext) :
  NativeRNFileUploaderSpec(context) {

  companion object {
    const val NAME = "RNFileUploader"
    const val TAG = "RNFileUploader.UploaderModule"
    const val WORKER_TAG = "RNFileUploader"
    // WorkInfo exposes tags but not the unique-work name, so the upload id is
    // also stored as a prefixed tag to recover it from a WorkInfo row.
    const val ID_TAG_PREFIX = "RNFileUploaderId:"
    // v10 slice 1 ships the JS layer alone. Every queue method rejects with
    // this code until slice 2 builds the Android queue and executor.
    const val E_NOT_IMPLEMENTED = "E_NOT_IMPLEMENTED"

    // The live module, so EventReporter can reach the codegen emitters — they are
    // protected on the generated spec, so only this class may call them. Null
    // whenever JS is absent (headless worker, mid-reload); terminal outcomes are
    // journaled before being emitted, so a dropped live event is never lost.
    //
    // Volatile: written on the module-creation thread and read from the
    // WorkManager worker, OkHttp callbacks and main, with no other barrier.
    @Volatile
    var instance: UploaderModule? = null
      private set
  }

  private val workManager = WorkManager.getInstance(context)

  init {
    instance = this
  }

  override fun invalidate() {
    // A reload constructs the replacement before tearing this one down, so only
    // clear the pointer when it still refers to us.
    if (instance === this) instance = null
    super.invalidate()
  }

  override fun getName(): String = NAME


  // MARK: - Event emission (called by EventReporter)

  // The v9 workers still report through these. The v10 spec has no per-outcome
  // emitters and a different progress shape ({ id, bytesSent, totalBytes }), so
  // until slice 2 rewires the workers to onState/onProgress/onSettled, the live
  // v9 payloads are dropped here. Terminal outcomes are journaled first, so
  // nothing durable is lost.
  fun emitProgressEvent(@Suppress("UNUSED_PARAMETER") params: WritableMap) = Unit

  fun emitCompletedEvent(@Suppress("UNUSED_PARAMETER") params: WritableMap) = Unit

  fun emitErrorEvent(@Suppress("UNUSED_PARAMETER") params: WritableMap) = Unit

  fun emitCancelledEvent(@Suppress("UNUSED_PARAMETER") params: WritableMap) = Unit

  fun emitNotificationEvent(params: WritableMap) = safeEmit { emitOnNotification(params) }

  private inline fun safeEmit(emit: () -> Unit) {
    try {
      emit()
    } catch (exc: NullPointerException) {
      // The generated spec's emitter callback is only installed when the C++
      // TurboModule is constructed, and is gone once the runtime tears down, so a
      // null callback is expected in both gaps. It is ALSO null for the whole
      // process on the old architecture, where this module still registers and its
      // methods work but no event can ever be delivered — hence warn, not debug,
      // so that case is diagnosable instead of silent.
      Log.w(TAG, "live event dropped (no event emitter — New Architecture required)")
    } catch (exc: Throwable) {
      // Anything else is a real bridging or payload failure worth seeing.
      Log.e(TAG, "failed to emit live event", exc)
    }
  }


  /**
   * Returns terminal events (completed/error/cancelled) that JS has not yet
   * acknowledged, including ones that fired while JS was dead. Read these on
   * startup, process them, then call ackEvents to remove them.
   */
  override fun getUnacknowledgedEvents(promise: Promise) {
    try {
      val events = EventJournal.get(reactApplicationContext).unacknowledged()
      val arr = Arguments.createArray()
      events.forEach { arr.pushMap(it.toWritableMap()) }
      promise.resolve(arr)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Removes journaled events by eventId once JS has processed them.
   */
  override fun ackEvents(ids: ReadableArray, promise: Promise) {
    try {
      val eventIds = (0 until ids.size()).mapNotNull { ids.getString(it) }
      val journal = EventJournal.get(reactApplicationContext)
      // An acknowledged 'completed' is the ONE moment when a chunked upload's
      // manifest and moved bytes may be deleted. Every other terminal keeps
      // them for a resume. Resolve which uploads those are before the entries
      // are removed.
      val completedUploadIds = journal.unacknowledged()
        .filter { it.type == "completed" && eventIds.contains(it.eventId) }
        .map { it.uploadId }
      journal.ack(eventIds)
      releaseAckedCompletions(
        completedUploadIds,
        ChunkedManifestStore.get(reactApplicationContext),
      ) { id -> workManager.cancelUniqueWork(id) }
      promise.resolve(true)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Synchronous. The live rows of the v10 queue. Slice 2 serializes them from
   * the in-memory index; until then the queue is empty.
   */
  override fun getRequests(): WritableArray = Arguments.createArray()


  /**
   * Saves the notification configuration (see [NotificationConfig]). Thus a
   * worker that WorkManager relaunches with no JS can read it. Each call
   * replaces the full configuration. An omitted field goes back to the library
   * default. The v10 `lifetimeMs` and `retry` fields ride along in the same
   * map; slice 2 persists them next to the queue.
   */
  override fun configure(options: ReadableMap) {
    NotificationConfig.save(reactApplicationContext, NotificationConfig.fromReadableMap(options))
  }


  // MARK: - v10 queue (stubs until slice 2)

  private fun notImplemented(promise: Promise, method: String) =
    promise.reject(E_NOT_IMPLEMENTED, "RNFileUploader.$method: the Android queue is not built yet")

  /** Persists { id, key, vars, descriptor } and schedules it. Slice 2. */
  override fun enqueue(entry: ReadableMap, promise: Promise) = notImplemented(promise, "enqueue")

  override fun pause(promise: Promise) = notImplemented(promise, "pause")

  override fun resume(promise: Promise) = notImplemented(promise, "resume")

  override fun cancel(id: String, promise: Promise) = notImplemented(promise, "cancel")

  override fun setWifiOnly(enabled: Boolean, promise: Promise) = notImplemented(promise, "setWifiOnly")

  override fun updateHeaders(patch: ReadableMap, promise: Promise) = notImplemented(promise, "updateHeaders")


  // MARK: - v9 enqueue paths, kept for slice 2 to wire behind enqueue()

  /**
   * @return the id of the enqueued upload
   */
  @Suppress("unused")
  private fun enqueueUpload(options: ReadableMap): String {
    val upload = Upload.fromReadableMap(options)
    val data = Gson().toJson(upload)

    // Clear any stale user-cancel mark for this (possibly reused) id
    // from a prior life, so a later system stop of this fresh upload isn't
    // misreported as a user cancel. Done here (before enqueue), never in the
    // worker, so a real cancel arriving as the worker starts can't be erased.
    UserCancellations.consume(upload.id)

    val request = OneTimeWorkRequestBuilder<UploadWorker>()
      .addTag(WORKER_TAG)
      .addTag(ID_TAG_PREFIX + upload.id)
      .setInputData(workDataOf(UploadWorker.PARAMS_KEY to data))
      .build()

    workManager
      // Using KEEP policy to prevent it from cancelling the work if it's already running.
      // Otherwise, it will emit "cancelled" and then go on to emit "progress" events,
      // which is confusing and quite difficult to manage. "cancelled" should be reserved for
      // when the user explicitly cancels the upload.
      .beginUniqueWork(upload.id, ExistingWorkPolicy.KEEP, request)
      .enqueue()

    return upload.id
  }


  /**
   * Starts, or resumes, a chunked upload. It is idempotent against the durable
   * [ChunkedManifest]. A first call takes ownership of the source file (an
   * O(1) rename into the library's directory) and persists the manifest. A
   * re-call with the same id reconciles instead: identical parts are required,
   * the stored headers are replaced, and the accepted parts are skipped. Crash
   * recovery, a resume after a stop, and a resume with fresh auth are all this
   * same call.
   */
  @Suppress("unused")
  private fun enqueueChunkedUpload(options: ReadableMap): String {
    val store = ChunkedManifestStore.get(reactApplicationContext)
    val id = options.getString("id")
      ?: throw Upload.MissingOptionException("id")
    val blob = store.blobFile(id)
    val incoming = ChunkedManifest.fromReadableMap(
      options,
      sourcePath = blob.absolutePath,
      createdAt = System.currentTimeMillis(),
    )

    // One atomic store operation, persisted BEFORE the work is enqueued. The
    // manifest is what a worker relaunched with no JS runs from. The store
    // lock spans load, reconcile, and save. Thus a running worker's
    // markAccepted can never land between them and be erased. The running flag
    // inside the lock is race-free too. A worker acquires ChunkedWorkerGate
    // before its first manifest read. Thus it either registers first (and the
    // recreate is rejected), or it reads the manifest that this call saved.
    store.compute(id) { existing ->
      if (existing == null) {
        val path = options.getString("path") ?: throw Upload.MissingOptionException("path")
        takeOwnership(File(path), blob)
        incoming
      } else {
        // `path` is deliberately ignored here. When a manifest exists, the
        // owned bytes are the source of truth.
        existing.reconcile(
          incoming,
          running = ChunkedWorkerGate.isRunning(id),
          blobSize = File(existing.sourcePath).length(),
        )
      }
    }

    // The stale-mark reasoning is the same as in enqueueUpload.
    UserCancellations.consume(id)

    // A queued successor (an unfinished row that is not RUNNING) already
    // guarantees a run after the current one finishes. An appended second run
    // would only stack duplicate no-op runs. The manifest reconcile above
    // still landed. That is how this call's fresh headers reach the queued
    // run.
    val states = workManager.getWorkInfosForUniqueWork(id).get().map { it.state }
    if (hasQueuedSuccessor(states)) return id

    val request = OneTimeWorkRequestBuilder<ChunkedUploadWorker>()
      .addTag(WORKER_TAG)
      .addTag(ID_TAG_PREFIX + id)
      .setInputData(workDataOf(ChunkedUploadWorker.ID_KEY to id))
      .build()

    // APPEND_OR_REPLACE, not KEEP. A worker journals its terminal error before
    // doWork returns. Thus a consumer that resumes from the error handler can
    // arrive while that run's row is still RUNNING. KEEP would silently drop
    // the resume, and nothing would ever run it. An append keeps the runs
    // strictly sequential, and a trailing run over an already-settled manifest
    // is a clean no-op (see ChunkedEngine.startAction). Appended work is a
    // chain DEPENDENT: WorkManager marks the dependents of a failed
    // prerequisite FAILED without a run. That is why ChunkedUploadWorker
    // always returns Result.success(), even after it journals a terminal error
    // (see terminalErrorResult). The OR_REPLACE half only rescues enqueues
    // that arrive AFTER the chain already settled failed or cancelled: it
    // starts a fresh sequence. A re-call while the worker runs still never
    // restarts it. The running worker re-reads the stored manifest before
    // every part attempt, so a resume's fresh headers reach it.
    workManager
      .beginUniqueWork(id, ExistingWorkPolicy.APPEND_OR_REPLACE, request)
      .enqueue()

    return id
  }

  @Suppress("unused")
  private fun takeOwnership(source: File, blob: File) {
    if (!source.exists()) {
      // A crash between the rename and the manifest save leaves the bytes at
      // the blob path with no manifest. Adopt them. Do not fail the retry.
      if (blob.exists()) return
      throw IllegalArgumentException("chunked source file does not exist: ${source.path}")
    }
    blob.parentFile?.mkdirs()
    if (blob.exists()) blob.delete()
    if (source.renameTo(blob)) return
    // renameTo cannot cross filesystems. Files.move falls back to copy+delete.
    Files.move(source.toPath(), blob.toPath(), StandardCopyOption.REPLACE_EXISTING)
  }
}

/**
 * Releases the uploads whose 'completed' events were just acknowledged. That
 * is the ONE moment when a chunked upload's manifest and moved bytes may be
 * deleted. The allAccepted guard protects a recreate: the id may have been
 * RECREATED (a different parts array under the same id) and run again over
 * these bytes. An ack of the old life's completion must not cancel that work,
 * and it must not delete the blob under it. Simple uploads have no manifest
 * and fall through untouched. A cancel of their unique work could kill an
 * unrelated new upload that reuses the id.
 */
internal fun releaseAckedCompletions(
  uploadIds: List<String>,
  store: ChunkedManifestStore,
  cancelWork: (String) -> Unit,
) {
  uploadIds.forEach { id ->
    val manifest = store.load(id) ?: return@forEach
    if (!manifest.allAccepted) return@forEach
    // Cancel a still-enqueued trailing run BEFORE the delete. A worker that
    // starts after the delete finds nothing. It exits silently, but there is
    // no reason to run it at all.
    cancelWork(id)
    store.remove(id)
  }
}

/**
 * Whether cancelUpload must journal and emit the 'cancelled' event itself.
 * That is the case only when NO row is RUNNING. A never-started row (ENQUEUED,
 * or BLOCKED as an appended chain's dependent) has no worker to run a stop
 * handler. A RUNNING worker's stop handler owns the report, including a worker
 * that still waits on the ChunkedWorkerGate.
 */
internal fun cancelReportsFromModule(unfinishedStates: List<WorkInfo.State>): Boolean =
  unfinishedStates.isNotEmpty() && unfinishedStates.none { it == WorkInfo.State.RUNNING }

/** An unfinished row that is not RUNNING: a queued run that did not start yet. */
internal fun hasQueuedSuccessor(states: List<WorkInfo.State>): Boolean =
  states.any { !it.isFinished && it != WorkInfo.State.RUNNING }

/**
 * One state for a chunked upload id, from all its WorkInfo rows plus the
 * durable manifest. A live row wins. With no live row, the manifest speaks.
 * The state is never "cancelled". iOS getAllUploads has no lingering cancelled
 * rows (a cancelled task leaves the session). And on Android, a cancelled
 * chunked upload keeps its manifest. Its truthful state is
 * stalled-awaiting-resume, that is, "error".
 */
internal fun chunkedUploadState(states: List<WorkInfo.State>, allAccepted: Boolean): String =
  when {
    WorkInfo.State.RUNNING in states -> "running"
    states.any { !it.isFinished } -> "pending"
    allAccepted -> "completed"
    else -> "error"
  }

/**
 * One state for a simple upload id, from all its WorkInfo rows. An id can have
 * a lingering finished chain next to a live one. A live row wins. Otherwise
 * the most conclusive finished state wins.
 */
internal fun simpleUploadState(states: List<WorkInfo.State>): String =
  when {
    WorkInfo.State.RUNNING in states -> "running"
    states.any { !it.isFinished } -> "pending"
    WorkInfo.State.SUCCEEDED in states -> "completed"
    WorkInfo.State.FAILED in states -> "error"
    else -> "cancelled"
  }
