package ai.openspace.backgroundupload

import android.util.Log
import androidx.work.ExistingWorkPolicy
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkInfo
import androidx.work.WorkManager
import androidx.work.workDataOf
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableArray
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap
import com.google.gson.Gson
import java.util.UUID


/**
 * TurboModule (New Architecture). [NativeRNFileUploaderSpec] is generated by
 * codegen from `src/NativeRNFileUploader.ts` into this same package (see
 * `codegenConfig.android.javaPackageName` in package.json), so it needs no import.
 */
class UploaderModule(context: ReactApplicationContext) :
  NativeRNFileUploaderSpec(context) {

  companion object {
    const val NAME = "RNFileUploader"
    const val TAG = "RNFileUploader.UploaderModule"
    const val WORKER_TAG = "RNFileUploader"
    // WorkInfo exposes tags but not the unique-work name, so the upload id is
    // also stored as a prefixed tag to recover it in getAllUploads.
    const val ID_TAG_PREFIX = "RNFileUploaderId:"

    // The live module, so EventReporter can reach the codegen emitters — they are
    // protected on the generated spec, so only this class may call them. Null
    // whenever JS is absent (headless worker, mid-reload); terminal outcomes are
    // journaled before being emitted, so a dropped live event is never lost.
    //
    // Volatile: written on the module-creation thread and read from the
    // WorkManager worker, OkHttp callbacks and main, with no other barrier.
    @Volatile
    var instance: UploaderModule? = null
      private set
  }

  private val workManager = WorkManager.getInstance(context)

  init {
    instance = this
  }

  override fun invalidate() {
    // A reload constructs the replacement before tearing this one down, so only
    // clear the pointer when it still refers to us.
    if (instance === this) instance = null
    super.invalidate()
  }

  override fun getName(): String = NAME


  // MARK: - Event emission (called by EventReporter)

  fun emitProgressEvent(params: WritableMap) = safeEmit { emitOnProgress(params) }

  fun emitCompletedEvent(params: WritableMap) = safeEmit { emitOnCompleted(params) }

  fun emitErrorEvent(params: WritableMap) = safeEmit { emitOnError(params) }

  fun emitCancelledEvent(params: WritableMap) = safeEmit { emitOnCancelled(params) }

  fun emitNotificationEvent(params: WritableMap) = safeEmit { emitOnNotification(params) }

  private inline fun safeEmit(emit: () -> Unit) {
    try {
      emit()
    } catch (exc: NullPointerException) {
      // The generated spec's emitter callback is only installed when the C++
      // TurboModule is constructed, and is gone once the runtime tears down, so a
      // null callback is expected in both gaps. It is ALSO null for the whole
      // process on the old architecture, where this module still registers and its
      // methods work but no event can ever be delivered — hence warn, not debug,
      // so that case is diagnosable instead of silent.
      Log.w(TAG, "live event dropped (no event emitter — New Architecture required)")
    } catch (exc: Throwable) {
      // Anything else is a real bridging or payload failure worth seeing.
      Log.e(TAG, "failed to emit live event", exc)
    }
  }


  /**
   * Returns terminal events (completed/error/cancelled) that JS has not yet
   * acknowledged, including ones that fired while JS was dead. Read these on
   * startup, process them, then call ackEvents to remove them.
   */
  override fun getUnacknowledgedEvents(promise: Promise) {
    try {
      val events = EventJournal.get(reactApplicationContext).unacknowledged()
      val arr = Arguments.createArray()
      events.forEach { arr.pushMap(it.toWritableMap()) }
      promise.resolve(arr)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Removes journaled events by eventId once JS has processed them.
   */
  override fun ackEvents(ids: ReadableArray, promise: Promise) {
    try {
      val eventIds = (0 until ids.size()).mapNotNull { ids.getString(it) }
      EventJournal.get(reactApplicationContext).ack(eventIds)
      promise.resolve(true)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Enumerates uploads WorkManager still knows about, as [{ id, state }].
   * WorkManager auto-prunes finished work after roughly a day, so this is for
   * reconciling live/recent uploads — terminal outcomes must be read from
   * getUnacknowledgedEvents, which is durable until acknowledged.
   */
  override fun getAllUploads(promise: Promise) {
    try {
      val infos = workManager.getWorkInfosByTag(WORKER_TAG).get()
      val arr = Arguments.createArray()
      for (info in infos) {
        val id = info.tags.firstOrNull { it.startsWith(ID_TAG_PREFIX) }
          ?.removePrefix(ID_TAG_PREFIX) ?: continue
        arr.pushMap(Arguments.createMap().apply {
          putString("id", id)
          putString(
            "state",
            when (info.state) {
              WorkInfo.State.ENQUEUED, WorkInfo.State.BLOCKED -> "pending"
              WorkInfo.State.RUNNING -> "running"
              WorkInfo.State.SUCCEEDED -> "completed"
              WorkInfo.State.FAILED -> "error"
              WorkInfo.State.CANCELLED -> "cancelled"
            },
          )
        })
      }
      promise.resolve(arr)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Saves the notification configuration (see [NotificationConfig]). Thus a
   * worker that WorkManager relaunches with no JS can read it. Each call
   * replaces the full configuration. An omitted field goes back to the library
   * default.
   */
  override fun configure(options: ReadableMap) {
    NotificationConfig.save(reactApplicationContext, NotificationConfig.fromReadableMap(options))
  }


  /*
   * Starts a file upload.
   * Returns a promise with the string ID of the upload.
   */
  override fun startUpload(options: ReadableMap, promise: Promise) {
    try {
      val id = enqueueUpload(options)
      promise.resolve(id)
    } catch (exc: Throwable) {
      if (exc !is Upload.MissingOptionException) {
        exc.printStackTrace()
        Log.e(TAG, exc.message, exc)
      }
      promise.reject(exc)
    }
  }

  /**
   * @return the id of the enqueued upload
   */
  private fun enqueueUpload(options: ReadableMap): String {
    val upload = Upload.fromReadableMap(options)
    val data = Gson().toJson(upload)

    // Clear any stale user-cancel mark for this (possibly reused) id
    // from a prior life, so a later system stop of this fresh upload isn't
    // misreported as a user cancel. Done here (before enqueue), never in the
    // worker, so a real cancel arriving as the worker starts can't be erased.
    UserCancellations.consume(upload.id)

    val request = OneTimeWorkRequestBuilder<UploadWorker>()
      .addTag(WORKER_TAG)
      .addTag(ID_TAG_PREFIX + upload.id)
      .setInputData(workDataOf(UploadWorker.PARAMS_KEY to data))
      .build()

    workManager
      // Using KEEP policy to prevent it from cancelling the work if it's already running.
      // Otherwise, it will emit "cancelled" and then go on to emit "progress" events,
      // which is confusing and quite difficult to manage. "cancelled" should be reserved for
      // when the user explicitly cancels the upload.
      .beginUniqueWork(upload.id, ExistingWorkPolicy.KEEP, request)
      .enqueue()

    return upload.id
  }


  /*
   * Cancels file upload
   * Accepts upload ID as a first argument, this upload will be cancelled
   * Event "cancelled" will be fired when upload is cancelled.
   */
  override fun cancelUpload(id: String, promise: Promise) {
    try {
      val active = workManager.getWorkInfosForUniqueWork(id).get()
        .firstOrNull { !it.state.isFinished }

      if (active == null) {
        // Nothing to cancel. Drop any mark so a later upload reusing this id
        // can't be misreported as a user cancel.
        UserCancellations.consume(id)
        promise.resolve(false)

        return
      }

      // Record intent BEFORE cancelling so the worker's stop handler can tell
      // this apart from a system stop and report cancelReason 'user'.
      UserCancellations.mark(id)
      workManager.cancelUniqueWork(id)

      if (active.state == WorkInfo.State.ENQUEUED) {
        // The worker never started, so it will never run its own stop handler and
        // nothing else would ever report this cancellation — leaving a consumer
        // awaiting this upload's outcome forever. Report it here instead, and
        // consume the mark so it cannot leak.
        UserCancellations.consume(id)
        val entry = EventJournal.Entry(
          eventId = UUID.randomUUID().toString(),
          uploadId = id,
          type = "cancelled",
          timestamp = System.currentTimeMillis(),
          cancelReason = "user",
        )
        EventJournal.get(reactApplicationContext).append(entry)
        EventReporter.emit(entry)
      }

      promise.resolve(true)
    } catch (exc: Throwable) {
      exc.printStackTrace()
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }

  // The chunked transport arrives in the platform changes that follow this
  // spec change. Until then, a rejection satisfies the codegen contract.
  override fun startChunkedUpload(options: ReadableMap, promise: Promise) {
    promise.reject("E_NOT_IMPLEMENTED", "Chunked uploads are not implemented in this build")
  }

  override fun removeUpload(id: String, promise: Promise) {
    promise.reject("E_NOT_IMPLEMENTED", "removeUpload is not implemented in this build")
  }
}
