package ai.openspace.backgroundupload

import android.util.Log
import androidx.work.ExistingWorkPolicy
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkInfo
import androidx.work.WorkManager
import androidx.work.workDataOf
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableArray
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap
import com.google.gson.Gson


/**
 * TurboModule (New Architecture). [NativeRNFileUploaderSpec] is generated by
 * codegen from `src/NativeRNFileUploader.ts` into this same package (see
 * `codegenConfig.android.javaPackageName` in package.json), so it needs no import.
 */
class UploaderModule(context: ReactApplicationContext) :
  NativeRNFileUploaderSpec(context) {

  companion object {
    const val NAME = "RNFileUploader"
    const val TAG = "RNFileUploader.UploaderModule"
    const val WORKER_TAG = "RNFileUploader"
    // WorkInfo exposes tags but not the unique-work name, so the upload id is
    // also stored as a prefixed tag to recover it in getAllUploads.
    const val ID_TAG_PREFIX = "RNFileUploaderId:"

    // The live module, so EventReporter can reach the codegen emitters — they are
    // protected on the generated spec, so only this class may call them. Null
    // whenever JS is absent (headless worker, mid-reload); terminal outcomes are
    // journaled before being emitted, so a dropped live event is never lost.
    var instance: UploaderModule? = null
      private set
  }

  private val workManager = WorkManager.getInstance(context)

  init {
    instance = this
  }

  override fun invalidate() {
    // A reload constructs the replacement before tearing this one down, so only
    // clear the pointer when it still refers to us.
    if (instance === this) instance = null
    super.invalidate()
  }

  override fun getName(): String = NAME


  // MARK: - Event emission (called by EventReporter)

  fun emitProgressEvent(params: WritableMap) = safeEmit { emitOnProgress(params) }

  fun emitCompletedEvent(params: WritableMap) = safeEmit { emitOnCompleted(params) }

  fun emitErrorEvent(params: WritableMap) = safeEmit { emitOnError(params) }

  fun emitCancelledEvent(params: WritableMap) = safeEmit { emitOnCancelled(params) }

  fun emitNotificationEvent(params: WritableMap) = safeEmit { emitOnNotification(params) }

  private inline fun safeEmit(emit: () -> Unit) {
    try {
      emit()
    } catch (exc: Throwable) {
      // The generated spec's emitter callback is null until JS attaches a
      // listener, and gone once the runtime tears down. Both are expected.
      Log.d(TAG, "live event skipped: ${exc.message}")
    }
  }


  /**
   * Returns terminal events (completed/error/cancelled) that JS has not yet
   * acknowledged, including ones that fired while JS was dead. Read these on
   * startup, process them, then call ackEvents to remove them.
   */
  override fun getUnacknowledgedEvents(promise: Promise) {
    try {
      val events = EventJournal.get(reactApplicationContext).unacknowledged()
      val arr = Arguments.createArray()
      events.forEach { arr.pushMap(it.toWritableMap()) }
      promise.resolve(arr)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Removes journaled events by eventId once JS has processed them.
   */
  override fun ackEvents(ids: ReadableArray, promise: Promise) {
    try {
      val eventIds = (0 until ids.size()).mapNotNull { ids.getString(it) }
      EventJournal.get(reactApplicationContext).ack(eventIds)
      promise.resolve(true)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * Enumerates uploads WorkManager still knows about, as [{ id, state }].
   * WorkManager auto-prunes finished work after roughly a day, so this is for
   * reconciling live/recent uploads — terminal outcomes must be read from
   * getUnacknowledgedEvents, which is durable until acknowledged.
   */
  override fun getAllUploads(promise: Promise) {
    try {
      val infos = workManager.getWorkInfosByTag(WORKER_TAG).get()
      val arr = Arguments.createArray()
      for (info in infos) {
        val id = info.tags.firstOrNull { it.startsWith(ID_TAG_PREFIX) }
          ?.removePrefix(ID_TAG_PREFIX) ?: continue
        arr.pushMap(Arguments.createMap().apply {
          putString("id", id)
          putString(
            "state",
            when (info.state) {
              WorkInfo.State.ENQUEUED, WorkInfo.State.BLOCKED -> "pending"
              WorkInfo.State.RUNNING -> "running"
              WorkInfo.State.SUCCEEDED -> "completed"
              WorkInfo.State.FAILED -> "error"
              WorkInfo.State.CANCELLED -> "cancelled"
            },
          )
        })
      }
      promise.resolve(arr)
    } catch (exc: Throwable) {
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }


  /**
   * iOS-only: there is no per-task byte counter to read on Android, where uploads
   * are WorkManager jobs rather than URLSession tasks. Use getAllUploads for
   * liveness and the progress event for bytes.
   */
  override fun getUploadStatus(id: String, promise: Promise) {
    promise.resolve(null)
  }


  /*
   * Starts a file upload.
   * Returns a promise with the string ID of the upload.
   */
  override fun startUpload(options: ReadableMap, promise: Promise) {
    try {
      val id = enqueueUpload(options)
      promise.resolve(id)
    } catch (exc: Throwable) {
      if (exc !is Upload.MissingOptionException) {
        exc.printStackTrace()
        Log.e(TAG, exc.message, exc)
      }
      promise.reject(exc)
    }
  }

  /**
   * @return the id of the enqueued upload
   */
  private fun enqueueUpload(options: ReadableMap): String {
    val upload = Upload.fromReadableMap(options)
    val data = Gson().toJson(upload)

    // Clear any stale user-cancel mark for this (possibly reused customUploadId)
    // from a prior life, so a later system stop of this fresh upload isn't
    // misreported as a user cancel. Done here (before enqueue), never in the
    // worker, so a real cancel arriving as the worker starts can't be erased.
    UserCancellations.consume(upload.id)

    val request = OneTimeWorkRequestBuilder<UploadWorker>()
      .addTag(WORKER_TAG)
      .addTag(ID_TAG_PREFIX + upload.id)
      .setInputData(workDataOf(UploadWorker.Input.Params.name to data))
      .build()

    workManager
      // Using KEEP policy to prevent it from cancelling the work if it's already running.
      // Otherwise, it will emit "cancelled" and then go on to emit "progress" events,
      // which is confusing and quite difficult to manage. "cancelled" should be reserved for
      // when the user explicitly cancels the upload.
      .beginUniqueWork(upload.id, ExistingWorkPolicy.KEEP, request)
      .enqueue()

    return upload.id
  }


  /*
   * Cancels file upload
   * Accepts upload ID as a first argument, this upload will be cancelled
   * Event "cancelled" will be fired when upload is cancelled.
   */
  override fun cancelUpload(id: String, promise: Promise) {
    try {
      // Record intent BEFORE cancelling so the worker's stop handler can tell
      // this apart from a system stop and report cancelReason 'user'.
      UserCancellations.mark(id)
      workManager.cancelUniqueWork(id)
      promise.resolve(true)
    } catch (exc: Throwable) {
      exc.printStackTrace()
      Log.e(TAG, exc.message, exc)
      promise.reject(exc)
    }
  }
}
